import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { demoApplicationState, type ApplicationFormState } from "../../features/application/engine";
import { PROCUREMENT_FIELDS } from "../../features/application/procurement";

const headers = { Origin: process.env.DGITA_E2E_BASE_URL! };
const estimateLabel = "Anslået samlet kontraktværdi ekskl. moms";
const durationLabel = "Kontraktperiode i måneder";
const optionsLabel = "Optioner og mulige forlængelser";
const noteLabel = "Grundlag for den anslåede kontraktværdi";
const referenceLabel = "Dokument- eller journalreference til eksisterende aftale";

test("legacy procurement gains explicit answers, accessible multi-categories, save/resume and immutable submission", async ({ page }, testInfo) => {
  test.setTimeout(75_000);
  const clientErrors: string[] = [];
  page.on("pageerror", (error) => clientErrors.push(error.message));
  await page.addInitScript(() => localStorage.setItem("dgita-onboarding-v1-complete", "true"));
  expect((await page.request.post("/api/auth/dev-login", { headers, data: { role: "user" } })).status()).toBe(200);
  const approver = (await (await page.request.get("/api/approvers")).json()).approvers[0];
  const draft: ApplicationFormState = { ...structuredClone(demoApplicationState), knownSystem: "nej", selectedSystem: null,
    manualSystemName: "Syntetisk anskaffelsesgrundlag", catalogQuery: "", consent: true, approvingLeaderId: approver.id, approvingLeader: approver.name };
  for (const field of PROCUREMENT_FIELDS) delete draft[field];
  delete draft.personalDataCategories;
  const savedResponse = await page.request.post("/api/drafts", { headers, data: { id: crypto.randomUUID(), draft, status: "draft" } });
  expect(savedResponse.status()).toBe(200);
  const saved = await savedResponse.json();
  const readDraft = async () => (await (await page.request.get(`/api/drafts?caseNumber=${saved.caseNumber}`)).json()).draft.state;
  await page.goto(`/?view=application&draft=${saved.caseNumber}`);
  await page.getByRole("button", { name: "Investering", exact: true }).click();
  const valueStatus = page.getByRole("radiogroup", { name: "Er den samlede kontraktværdi anslået?", exact: true });
  const coverage = page.getByRole("radiogroup", { name: "Hvordan dækkes anskaffelsen af en aftale?", exact: true });
  await expect(valueStatus.getByRole("radio", { checked: true })).toHaveCount(0);
  await expect(coverage.getByRole("radio", { checked: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Fortsæt", exact: true }).click();
  await expect(valueStatus).toHaveAttribute("aria-invalid", "true");
  await expect(valueStatus).toHaveAccessibleDescription(/kontraktværdien er anslået eller skal afklares/);
  await valueStatus.getByRole("radio", { name: "Værdien er anslået", exact: true }).click();
  await coverage.getByRole("radio", { name: "Eksisterende aftale", exact: true }).click();
  const amount = page.getByRole("textbox", { name: estimateLabel, exact: true });
  await amount.fill("1,234.56");
  await page.getByRole("button", { name: "Fortsæt", exact: true }).click();
  await expect(amount).toHaveAttribute("aria-invalid", "true");
  await expect(amount).toHaveAccessibleDescription(/Brug dansk beløbsformat/);
  await amount.fill("725.000,00");
  await page.getByRole("textbox", { name: durationLabel, exact: true }).fill("36");
  await page.getByRole("textbox", { name: optionsLabel, exact: true }).fill("Ingen");
  await page.getByRole("textbox", { name: noteLabel, exact: true }).fill("Etablering og 36 måneders drift ekskl. moms.");
  await page.getByRole("textbox", { name: referenceLabel, exact: true }).fill("Journal 2026-123 / aftale A");
  await page.getByRole("button", { name: "Gem kladde", exact: true }).click();
  await expect.poll(async () => (await readDraft()).estimatedContractValueExVat).toBe("725.000,00");
  await page.reload();
  await page.getByRole("button", { name: "Investering", exact: true }).click();
  await expect(amount).toHaveValue("725.000,00");
  await expect(page.getByRole("textbox", { name: referenceLabel, exact: true })).toHaveValue("Journal 2026-123 / aftale A");
  await page.evaluate(async () => { await Promise.all(document.getAnimations().filter((animation) => animation.effect?.getComputedTiming().iterations !== Infinity).map((animation) => animation.finished.catch(() => {}))); });
  expect((await new AxeBuilder({ page }).include(".application-sheet").withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"]).analyze()).violations).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("procurement-desktop.png"), fullPage: true });
  await page.getByRole("button", { name: "Fortsæt", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Risiko & data", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Fortsæt", exact: true }).click();
  const categories = page.getByRole("group", { name: "Personoplysningskategorier", exact: true });
  const ordinary = categories.getByRole("checkbox", { name: "Almindelige personoplysninger", exact: true });
  await expect(ordinary).toHaveAttribute("aria-invalid", "true");
  await ordinary.focus();
  await page.keyboard.press("Space");
  await expect(ordinary).toBeChecked();
  await categories.getByRole("checkbox", { name: "Særlige kategorier (følsomme oplysninger)", exact: true }).check();
  await categories.getByRole("checkbox", { name: "CPR-numre", exact: true }).check();
  await page.setViewportSize({ width: 390, height: 844 });
  await categories.scrollIntoViewIfNeeded();
  expect((await new AxeBuilder({ page }).include(".application-sheet").withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"]).analyze()).violations).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("data-categories-mobile.png"), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole("button", { name: "Gem kladde", exact: true }).click();
  await expect.poll(async () => (await readDraft()).personalDataCategories).toEqual(["ordinary", "special", "national-id"]);
  await page.reload();
  await page.getByRole("button", { name: "Risiko & data", exact: true }).click();
  await expect(ordinary).toBeChecked();
  await page.getByRole("button", { name: "Gennemse", exact: true }).click();
  await expect(page.locator(".review-line").filter({ hasText: estimateLabel })).toContainText("725.000,00 kr.");
  await expect(page.locator(".review-line").filter({ hasText: "Personoplysningskategorier" })).toContainText("CPR-numre");
  const submittedResponse = page.waitForResponse((response) => response.url().endsWith("/api/drafts") && response.request().postDataJSON()?.status === "submitted");
  await page.getByRole("button", { name: "Gem og indsend", exact: true }).click();
  const response = await submittedResponse;
  expect(response.status()).toBe(200);
  const submitted = await response.json();
  const detailPath = `/api/cases/${submitted.caseNumber}/detail`;
  const detail = await (await page.request.get(detailPath)).json();
  expect(detail.snapshot.personalDataCategories).toEqual(["ordinary", "special", "national-id"]);
  expect(detail.snapshot.estimatedContractValueExVat).toBe("725.000,00");
  expect(detail.snapshot.contractOptionsDescription).toBe("Ingen");
  expect(detail.snapshot.agreementReference).toBe("Journal 2026-123 / aftale A");
  expect(detail.case.status).not.toBe("approved");
  expect((await (await page.request.get(detailPath)).json()).snapshot).toEqual(detail.snapshot);
  expect(clientErrors).toEqual([]);
});

test("uncertain procurement and personal-data No clear hidden answers and remain accessible on mobile", async ({ page }, testInfo) => {
  await page.addInitScript(() => localStorage.setItem("dgita-onboarding-v1-complete", "true"));
  expect((await page.request.post("/api/auth/dev-login", { headers, data: { role: "user" } })).status()).toBe(200);
  const draft: ApplicationFormState = { ...structuredClone(demoApplicationState), knownSystem: "nej", selectedSystem: null, manualSystemName: "Syntetisk uafklaret anskaffelse", consent: true, contractCoverage: "existing-agreement", agreementReference: "Journal 123" };
  const saved = await (await page.request.post("/api/drafts", { headers, data: { id: crypto.randomUUID(), draft, status: "draft" } })).json();
  const readDraft = async () => (await (await page.request.get(`/api/drafts?caseNumber=${saved.caseNumber}`)).json()).draft.state;
  await page.goto(`/?view=application&draft=${saved.caseNumber}`);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Investering", exact: true }).click();
  const valueStatus = page.getByRole("radiogroup", { name: "Er den samlede kontraktværdi anslået?", exact: true });
  const coverage = page.getByRole("radiogroup", { name: "Hvordan dækkes anskaffelsen af en aftale?", exact: true });
  await valueStatus.getByRole("radio", { name: "Skal afklares", exact: true }).click();
  await coverage.getByRole("radio", { name: "Skal afklares", exact: true }).click();
  await expect(page.getByRole("textbox", { name: estimateLabel, exact: true })).toHaveCount(0);
  await expect(page.getByRole("textbox", { name: referenceLabel, exact: true })).toHaveCount(0);
  await expect(page.getByText(/Afklar kontraktværdi og aftaleform med kommunens indkøbsansvarlige/)).toBeVisible();
  expect((await new AxeBuilder({ page }).include(".application-sheet").withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"]).analyze()).violations).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("procurement-mobile.png"), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole("button", { name: "Fortsæt", exact: true }).click();
  await page.getByRole("radiogroup", { name: "43. Behandler IT-systemet persondata?", exact: true }).getByRole("radio", { name: "Nej", exact: true }).click();
  await expect(page.getByRole("group", { name: "Personoplysningskategorier", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Gem kladde", exact: true }).click();
  await expect.poll(async () => (await readDraft()).personalDataCategories).toEqual([]);
  for (const field of ["estimatedContractValueExVat", "contractDurationMonths", "contractOptionsDescription", "contractValueNote", "agreementReference"]) await expect.poll(async () => (await readDraft())[field]).toBe("");
  await page.getByRole("button", { name: "Investering", exact: true }).click();
  await valueStatus.getByRole("radio", { name: "Værdien er anslået", exact: true }).click();
  await expect(page.getByRole("textbox", { name: estimateLabel, exact: true })).toHaveValue("");
  await coverage.getByRole("radio", { name: "Eksisterende aftale", exact: true }).click();
  await expect(page.getByRole("textbox", { name: referenceLabel, exact: true })).toHaveValue("");
});
